[package]
name = "futures-tokio-compat"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies]
futures-core = "0.3.4"
futures-io = "0.3.4"
tokio = "0.2.11"
#tokio-executor = ""
log = "0.4.8"
pin-project = "0.4.6"
